version: '3.8'

services: 
  source_postgres: 
    image: postgres:16.3
    ports: 
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: startdb
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  final_postgres: 
    image: postgres:16.3
    ports:  
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: final_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: finaldb
  
  elt_script:
    build: 
      context: ./elt
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - final_postgres

networks:
  elt_network:
    driver: bridge
